### PR TITLE
Change maintainer username from @astrofrog-conda-forge to @astrofrog

### PR DESCRIPTION
**Pull request by astrofrog**
This is to update my username from @astrofrog-conda-forge to @astrofrog - I used to have a separate username back when being a member of any conda-forge repository meant that I saw all conda-forge repositories on Travis CI but this is no longer relevant.

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by astrofrog** [comment]
@mwcraig - any idea what is going on with the failed builds here?

**Comment by mwcraig** [comment]
No idea -- I'm planning to look in the morning

**Comment by mwcraig** [comment]
Best guess is that jupyter-packaging is way out of date, and it sounds like I should switch to hatch: https://blog.jupyter.org/packaging-for-jupyter-in-2022-c7be64c38926

Will try in the morning locally, but fixing this might require a new release...

**Comment by mwcraig** [comment]
Updating jupyter-packaging fixed one thing but let to a bunch of other errors (typescript suddenly wants semicolons everywhere 🙄 ).

I'll try to get a build working over the weekend.

**Comment by mwcraig** [comment]
Root cause is an old version of typescript in `package.json`, new release coming soon that fixes that and updates the build system...

**Pull request closed without merging**
