### PR TITLE
 Add pre/post steps to enable/disable Jupyter extension

### LINKED ISSUE #1: pre-unlink and post-link steps missing
Packages for other Jupyter widgets in conda-forge (e.g. ipyvolume) include the enabling of the extension as a post-link step. Would it be possible to add this here too? (at the moment this is stopping me from using ipyevents on binder)

### PR DESCRIPTION
**Pull request by astrofrog**
@mwcraig - I also re-rendered the feedstock. This shouldn't make Python 2 builds.

Closes #1

### CODE REVIEW

**Comment by mwcraig** [comment]
@astrofrog -- I'll debug the fails on Wednesday....

**Comment by mwcraig** [comment]
The issue turned out to be that conda build 2.1.18 was not picking up the python dependency because of the version number. Adding python twice "fixed" that. 

@astrofrog -- are you ok with being added as a maintainer here?

**Comment by astrofrog** [comment]
@mwcraig - yes, that's fine by me!

**Comment by mwcraig** [comment]
@conda-forge-admin, please update team

**Comment by jakirkham** [comment]
It won't add him until his handle is listed in `master`.

**Comment by mwcraig** [comment]
@conda-forge-admin, please update team

**Comment by mwcraig** [comment]
Thanks for explaining that, @jakirkham

**Comment by jakirkham** [comment]
np. FWIW it should happen automatically when the PR is merged. IOW no action should be required on your part. However if that is not the case, please let @isuruf and myself know.

**Pull request merged**
